apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-k8s
  description: Repository for test Kubernetes stuff
  annotations:
    github.com/project-slug: 'sarafonseca-123/test-k8s'
  tags: [kubernetes, python, devops]
  links:
    - url: https://dashboard.example.com
      title: Dashboard - Kubernetes Monitoring
      icon: dashboard
spec:
  type: service
  lifecycle: production
  system: juspipeline
  owner: infra
  dependsOn: [component:dagster-demo]
